apiVersion: v1
kind: Service
metadata:
  name: django-web01
  namespace: default
spec:
  type: NodePort
  selector:
    app: django-web01
  ports:
  - name: http
    nodePort: 9527
    port: 8080
    targetPort: 8080
